# Generated by Django 3.2 on 2021-04-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas_vicky',
            name='acierto',
            field=models.TextField(max_length=10),
        ),
    ]
