# Generated by Django 3.2 on 2021-05-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicky', '0002_alter_preguntas_vicky_acierto'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(max_length=100)),
                ('comentario', models.TextField(max_length=200)),
            ],
        ),
    ]
